spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  sql:
    init:
      mode: always
      #schema-locations: classpath:schema.sql
      #data-locations: classpath:data.sql
  security:
    jwt:
      token:
        secret-key: chocolleto
        expire-length: 6000000